### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by claudiosousa** [nobuhito/vscode.printcode#1]
installed it on VS under Ubuntu.

When triggering the PrintCode command nothing happens. No message in the output window, no error in the developer tools

**Comment by nobuhito** [comment]
Thank you for reporting the problem.

In linux, `xdg.open` is set to start temporary files.

```
            case "linux":
                child_process.exec("xdg.open " + tempFile);
                break;
```

However, `xdg-open` seems to be more appropriate.

Is it possible to open `hogehoge.html` with` xdg-open hogehoge.html` from the command line?

I currently do not have a Linux environment with a GUI, so I hope you have a try and give me a reply.

**Comment by claudiosousa** [comment]
Thanks for your quick answer.

Tried opening an html file with "xdg-open filename.html" from the command line and it worked fine, opennig a new tag in my already opened browser.

Could you release a quick fix?

**Comment by nobuhito** [comment]
Thank you for confirmation! We will update it today!

("New tag" is a typo on "new tab", is not it?)

**Comment by claudiosousa** [comment]
Yes, I meant "tag". 

I just tried your latest version and it works perfectly 

It deserves a 5 star review :+1: 

Thank you for the help and quick reaction

**Comment by nobuhito** [comment]
Thank you so much!!!!!
