### ISSUE TITLE
More print options

### ISSUE THREAD

**Issue by kingvagabond** [nobuhito/vscode.printcode#16]
Right now it cannot print in landscape orientation, even switch to system print dialog. Any solution ? Thanks.

**Comment by janilahti** [comment]
@nobuhito Should some of the open issues be closed by you if the the person who raised the issue has left it hanging? For example this has been addressed in #6 .

**Comment by nobuhito** [comment]
I thought it was a different problem from # 6 as seen from the time axis. We will close once, please open again if there is still a problem. .
