### ISSUE TITLE
Color syntax between differents languages

### ISSUE THREAD

**Issue by glcraft** [nobuhito/vscode.printcode#17]
The color syntax in some languages isn't properly printed, even not in some case. 
In C++, there are only comments and number. In markdown, code blocks look like comments.
Then i installed a extension which change color of parenthesis each level of them.

So, is it possible to get the "VS Theme", kind of ?

EDIT: I just looked the source, it seems that the extension uses _codemirror_ to color the text. I'm not an expert of vscode API but I'm sure there's a way to retrieve color data from the document and build your own HTML from these values.

**Comment by nobuhito** [comment]
I also wanted to implement that idea, but it was difficult and gave up.
