### ISSUE TITLE
Word Wrap

### ISSUE THREAD

**Issue by jscooksey** [nobuhito/vscode.printcode#28]
Having an issue with word wrap when printing.  I'm printing to A4 size paper but PrintCode doesn't seem to include the full width of the paper for the code.  It wraps the text, almost at half way across the page.
If I increase or decrease the font size it still wraps at that mid point across the page.
This shows the same in Chrome and Firefox
![firefoxwebpage](https://user-images.githubusercontent.com/18700514/50381744-dbb5a180-06e2-11e9-9bda-c1048de492c0.PNG)
![chromewebpage](https://user-images.githubusercontent.com/18700514/50381745-dbb5a180-06e2-11e9-80f4-0f649fe8d44f.PNG)
![chromeprintpreview](https://user-images.githubusercontent.com/18700514/50381746-dbb5a180-06e2-11e9-9cda-0f3ab630a90f.PNG)
![chromeprintpreview](https://user-images.githubusercontent.com/18700514/50381751-fd168d80-06e2-11e9-87f7-a39873d50cda.PNG)

**Comment by MorphBC** [comment]
.vscode/extensions/nobuhito.printcode-3.0.0/src/content.js
line 152

**Comment by MorphBC** [comment]
BUt u can also try to choose A3 instead of A4.
