### ISSUE TITLE
Add Configuration to use non-default browser

### ISSUE THREAD

**Issue by AndrewMorris-2** [nobuhito/vscode.printcode#3]
Thank you for the clever workaround to fix the glaring miss on Microsoft's part as it pertains to print functionality!

There does, however, seem to be an issue with non-edge IE and this extension. 

Could you create a configuration that would allow a user to select which browser to use? I'm not quite sure how this could be achieved, or if it is even possible.

**Comment by nobuhito** [comment]
Hi
With the Ver.2 released earlier, it was possible to specify the browser. Please check it after updating.

Thnks.

**Comment by AndrewMorris-2** [comment]
Still have an issue with older IE, but now I can have it use Chrome instead. **Thanks!**

As info, the configuration will look something like this in the vsCode config file: 
`"printcode.browserPath": "C:/Program Files (x86)/Google/Chrome/Application/chrome.exe"`

**Comment by nobuhito** [comment]
You are welcome.
I appreciate it if you receive evaluation. 😄 

https://marketplace.visualstudio.com/items?itemName=nobuhito.printcode#review-details
