### ISSUE TITLE
Print PHP

### ISSUE THREAD

**Issue by supperpiecheese** [nobuhito/vscode.printcode#8]
![image](https://user-images.githubusercontent.com/16927633/37973576-d3891cf4-31a8-11e8-9ea0-1a9d9bc52924.png)
Every time I try to print a PHP page I get a blank page.

**Comment by catearcher** [comment]
This seems to only affect PHP files. CSS and JavaScript files work fine.

**Comment by janilahti** [comment]
@catearcher good point. Codemirror maps file type `php` to mode `php` (while for example `asp` gets mapped to `htmlembedded`), and for php mode we need to include some files on the generated print page.

I'll fix this and submit a PR hoping it'll get merged soon, but it seems for some reason @nobuhito is currently not active with this project.

There's an easy fix if you want to do it by hand while waiting for PRs to go through: Replace the last line of function `resolveAliases(language)` in file `~/.vscode/extensions/nobuhito.printcode-{version}/src/extension.js` with
```return table[language] === 'php' ? 'htmlembedded' : table[language];```

This will lose syntax coloring of PHP, but at least you see your code on paper.

**Comment by supperpiecheese** [comment]
Thanks for the help! I was taking a peek at the code and it seems like this fix works!
